### YamlMime:ManagedReference
items:
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass
  commentId: T:Sdl.MultiTerm.TMO.Interop.ApplicationClass
  id: ApplicationClass
  parent: Sdl.MultiTerm.TMO.Interop
  children:
  - Sdl.MultiTerm.TMO.Interop.ApplicationClass.#ctor
  - Sdl.MultiTerm.TMO.Interop.ApplicationClass.LocalRepository
  - Sdl.MultiTerm.TMO.Interop.ApplicationClass.MultiSearch
  - Sdl.MultiTerm.TMO.Interop.ApplicationClass.ServerRepository
  langs:
  - csharp
  - vb
  name: ApplicationClass
  nameWithType: ApplicationClass
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass
  type: Class
  assemblies:
  - Sdl.MultiTerm.TMO.Interop
  namespace: Sdl.MultiTerm.TMO.Interop
  syntax:
    content: >-
      [Guid("7D28407C-C491-4F46-ACFA-4589BBA4E490")]

      [ClassInterface(ClassInterfaceType.None)]

      public class ApplicationClass : Application, IApplication
    content.vb: >-
      <Guid("7D28407C-C491-4F46-ACFA-4589BBA4E490")>

      <ClassInterface(ClassInterfaceType.None)>

      Public Class ApplicationClass Implements Application, IApplication
  inheritance:
  - System.Object
  implements:
  - Sdl.MultiTerm.TMO.Interop.Application
  - Sdl.MultiTerm.TMO.Interop.IApplication
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 7D28407C-C491-4F46-ACFA-4589BBA4E490
  - type: System.Runtime.InteropServices.ClassInterfaceAttribute
    ctor: System.Runtime.InteropServices.ClassInterfaceAttribute.#ctor(System.Runtime.InteropServices.ClassInterfaceType)
    arguments:
    - type: System.Runtime.InteropServices.ClassInterfaceType
      value: 0
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass.#ctor
  commentId: M:Sdl.MultiTerm.TMO.Interop.ApplicationClass.#ctor
  id: '#ctor'
  parent: Sdl.MultiTerm.TMO.Interop.ApplicationClass
  langs:
  - csharp
  - vb
  name: ApplicationClass()
  nameWithType: ApplicationClass.ApplicationClass()
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass.ApplicationClass()
  type: Constructor
  assemblies:
  - Sdl.MultiTerm.TMO.Interop
  namespace: Sdl.MultiTerm.TMO.Interop
  syntax:
    content: public ApplicationClass()
    content.vb: Public Sub New()
  overload: Sdl.MultiTerm.TMO.Interop.ApplicationClass.#ctor*
  nameWithType.vb: ApplicationClass.New()
  fullName.vb: Sdl.MultiTerm.TMO.Interop.ApplicationClass.New()
  name.vb: New()
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass.LocalRepository
  commentId: P:Sdl.MultiTerm.TMO.Interop.ApplicationClass.LocalRepository
  id: LocalRepository
  isEii: true
  parent: Sdl.MultiTerm.TMO.Interop.ApplicationClass
  langs:
  - csharp
  - vb
  name: LocalRepository
  nameWithType: ApplicationClass.LocalRepository
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass.LocalRepository
  type: Property
  assemblies:
  - Sdl.MultiTerm.TMO.Interop
  namespace: Sdl.MultiTerm.TMO.Interop
  example: []
  syntax:
    content: virtual TermbaseRepository LocalRepository { get; }
    parameters: []
    return:
      type: Sdl.MultiTerm.TMO.Interop.TermbaseRepository
    content.vb: Overridable ReadOnly Property LocalRepository As TermbaseRepository
  overload: Sdl.MultiTerm.TMO.Interop.ApplicationClass.LocalRepository*
  implements:
  - Sdl.MultiTerm.TMO.Interop.IApplication.LocalRepository
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass.ServerRepository
  commentId: P:Sdl.MultiTerm.TMO.Interop.ApplicationClass.ServerRepository
  id: ServerRepository
  isEii: true
  parent: Sdl.MultiTerm.TMO.Interop.ApplicationClass
  langs:
  - csharp
  - vb
  name: ServerRepository
  nameWithType: ApplicationClass.ServerRepository
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass.ServerRepository
  type: Property
  assemblies:
  - Sdl.MultiTerm.TMO.Interop
  namespace: Sdl.MultiTerm.TMO.Interop
  example: []
  syntax:
    content: virtual TermbaseRepository ServerRepository { get; }
    parameters: []
    return:
      type: Sdl.MultiTerm.TMO.Interop.TermbaseRepository
    content.vb: Overridable ReadOnly Property ServerRepository As TermbaseRepository
  overload: Sdl.MultiTerm.TMO.Interop.ApplicationClass.ServerRepository*
  implements:
  - Sdl.MultiTerm.TMO.Interop.IApplication.ServerRepository
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass.MultiSearch
  commentId: P:Sdl.MultiTerm.TMO.Interop.ApplicationClass.MultiSearch
  id: MultiSearch
  isEii: true
  parent: Sdl.MultiTerm.TMO.Interop.ApplicationClass
  langs:
  - csharp
  - vb
  name: MultiSearch
  nameWithType: ApplicationClass.MultiSearch
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass.MultiSearch
  type: Property
  assemblies:
  - Sdl.MultiTerm.TMO.Interop
  namespace: Sdl.MultiTerm.TMO.Interop
  example: []
  syntax:
    content: virtual MultiSearch MultiSearch { get; }
    parameters: []
    return:
      type: Sdl.MultiTerm.TMO.Interop.MultiSearch
    content.vb: Overridable ReadOnly Property MultiSearch As MultiSearch
  overload: Sdl.MultiTerm.TMO.Interop.ApplicationClass.MultiSearch*
  implements:
  - Sdl.MultiTerm.TMO.Interop.IApplication.MultiSearch
references:
- uid: Sdl.MultiTerm.TMO.Interop
  commentId: N:Sdl.MultiTerm.TMO.Interop
  isExternal: true
  href: Sdl.html
  name: Sdl.MultiTerm.TMO.Interop
  nameWithType: Sdl.MultiTerm.TMO.Interop
  fullName: Sdl.MultiTerm.TMO.Interop
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.MultiTerm
    name: MultiTerm
    isExternal: true
    href: Sdl.MultiTerm.html
  - name: .
  - uid: Sdl.MultiTerm.TMO
    name: TMO
    isExternal: true
    href: Sdl.MultiTerm.TMO.html
  - name: .
  - uid: Sdl.MultiTerm.TMO.Interop
    name: Interop
    isExternal: true
    href: Sdl.MultiTerm.TMO.Interop.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.MultiTerm
    name: MultiTerm
    isExternal: true
    href: Sdl.MultiTerm.html
  - name: .
  - uid: Sdl.MultiTerm.TMO
    name: TMO
    isExternal: true
    href: Sdl.MultiTerm.TMO.html
  - name: .
  - uid: Sdl.MultiTerm.TMO.Interop
    name: Interop
    isExternal: true
    href: Sdl.MultiTerm.TMO.Interop.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Sdl.MultiTerm.TMO.Interop.Application
  commentId: T:Sdl.MultiTerm.TMO.Interop.Application
  parent: Sdl.MultiTerm.TMO.Interop
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.Application.html
  name: Application
  nameWithType: Application
  fullName: Sdl.MultiTerm.TMO.Interop.Application
- uid: Sdl.MultiTerm.TMO.Interop.IApplication
  commentId: T:Sdl.MultiTerm.TMO.Interop.IApplication
  parent: Sdl.MultiTerm.TMO.Interop
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.IApplication.html
  name: IApplication
  nameWithType: IApplication
  fullName: Sdl.MultiTerm.TMO.Interop.IApplication
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass.#ctor*
  commentId: Overload:Sdl.MultiTerm.TMO.Interop.ApplicationClass.#ctor
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.ApplicationClass.html#Sdl_MultiTerm_TMO_Interop_ApplicationClass__ctor
  name: ApplicationClass
  nameWithType: ApplicationClass.ApplicationClass
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass.ApplicationClass
  nameWithType.vb: ApplicationClass.New
  fullName.vb: Sdl.MultiTerm.TMO.Interop.ApplicationClass.New
  name.vb: New
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass.LocalRepository*
  commentId: Overload:Sdl.MultiTerm.TMO.Interop.ApplicationClass.LocalRepository
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.ApplicationClass.html#Sdl_MultiTerm_TMO_Interop_ApplicationClass_LocalRepository
  name: LocalRepository
  nameWithType: ApplicationClass.LocalRepository
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass.LocalRepository
- uid: Sdl.MultiTerm.TMO.Interop.IApplication.LocalRepository
  commentId: P:Sdl.MultiTerm.TMO.Interop.IApplication.LocalRepository
  parent: Sdl.MultiTerm.TMO.Interop.IApplication
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.IApplication.html#Sdl_MultiTerm_TMO_Interop_IApplication_LocalRepository
  name: LocalRepository
  nameWithType: IApplication.LocalRepository
  fullName: Sdl.MultiTerm.TMO.Interop.IApplication.LocalRepository
- uid: Sdl.MultiTerm.TMO.Interop.TermbaseRepository
  commentId: T:Sdl.MultiTerm.TMO.Interop.TermbaseRepository
  parent: Sdl.MultiTerm.TMO.Interop
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.TermbaseRepository.html
  name: TermbaseRepository
  nameWithType: TermbaseRepository
  fullName: Sdl.MultiTerm.TMO.Interop.TermbaseRepository
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass.ServerRepository*
  commentId: Overload:Sdl.MultiTerm.TMO.Interop.ApplicationClass.ServerRepository
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.ApplicationClass.html#Sdl_MultiTerm_TMO_Interop_ApplicationClass_ServerRepository
  name: ServerRepository
  nameWithType: ApplicationClass.ServerRepository
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass.ServerRepository
- uid: Sdl.MultiTerm.TMO.Interop.IApplication.ServerRepository
  commentId: P:Sdl.MultiTerm.TMO.Interop.IApplication.ServerRepository
  parent: Sdl.MultiTerm.TMO.Interop.IApplication
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.IApplication.html#Sdl_MultiTerm_TMO_Interop_IApplication_ServerRepository
  name: ServerRepository
  nameWithType: IApplication.ServerRepository
  fullName: Sdl.MultiTerm.TMO.Interop.IApplication.ServerRepository
- uid: Sdl.MultiTerm.TMO.Interop.ApplicationClass.MultiSearch*
  commentId: Overload:Sdl.MultiTerm.TMO.Interop.ApplicationClass.MultiSearch
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.ApplicationClass.html#Sdl_MultiTerm_TMO_Interop_ApplicationClass_MultiSearch
  name: MultiSearch
  nameWithType: ApplicationClass.MultiSearch
  fullName: Sdl.MultiTerm.TMO.Interop.ApplicationClass.MultiSearch
- uid: Sdl.MultiTerm.TMO.Interop.IApplication.MultiSearch
  commentId: P:Sdl.MultiTerm.TMO.Interop.IApplication.MultiSearch
  parent: Sdl.MultiTerm.TMO.Interop.IApplication
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.IApplication.html#Sdl_MultiTerm_TMO_Interop_IApplication_MultiSearch
  name: MultiSearch
  nameWithType: IApplication.MultiSearch
  fullName: Sdl.MultiTerm.TMO.Interop.IApplication.MultiSearch
- uid: Sdl.MultiTerm.TMO.Interop.MultiSearch
  commentId: T:Sdl.MultiTerm.TMO.Interop.MultiSearch
  parent: Sdl.MultiTerm.TMO.Interop
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.MultiSearch.html
  name: MultiSearch
  nameWithType: MultiSearch
  fullName: Sdl.MultiTerm.TMO.Interop.MultiSearch
