### YamlMime:ManagedReference
items:
- uid: Sdl.MultiTerm.TMO.Interop.Application
  commentId: T:Sdl.MultiTerm.TMO.Interop.Application
  id: Application
  parent: Sdl.MultiTerm.TMO.Interop
  children: []
  langs:
  - csharp
  - vb
  name: Application
  nameWithType: Application
  fullName: Sdl.MultiTerm.TMO.Interop.Application
  type: Interface
  assemblies:
  - Sdl.MultiTerm.TMO.Interop
  namespace: Sdl.MultiTerm.TMO.Interop
  syntax:
    content: >-
      [Guid("C5E2A9FA-583E-40BD-9480-DE623958C177")]

      public interface Application : IApplication
    content.vb: >-
      <Guid("C5E2A9FA-583E-40BD-9480-DE623958C177")>

      Public Interface Application Inherits IApplication
  inheritedMembers:
  - Sdl.MultiTerm.TMO.Interop.IApplication.LocalRepository
  - Sdl.MultiTerm.TMO.Interop.IApplication.ServerRepository
  - Sdl.MultiTerm.TMO.Interop.IApplication.MultiSearch
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: C5E2A9FA-583E-40BD-9480-DE623958C177
references:
- uid: Sdl.MultiTerm.TMO.Interop
  commentId: N:Sdl.MultiTerm.TMO.Interop
  isExternal: true
  href: Sdl.html
  name: Sdl.MultiTerm.TMO.Interop
  nameWithType: Sdl.MultiTerm.TMO.Interop
  fullName: Sdl.MultiTerm.TMO.Interop
  spec.csharp:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.MultiTerm
    name: MultiTerm
    isExternal: true
    href: Sdl.MultiTerm.html
  - name: .
  - uid: Sdl.MultiTerm.TMO
    name: TMO
    isExternal: true
    href: Sdl.MultiTerm.TMO.html
  - name: .
  - uid: Sdl.MultiTerm.TMO.Interop
    name: Interop
    isExternal: true
    href: Sdl.MultiTerm.TMO.Interop.html
  spec.vb:
  - uid: Sdl
    name: Sdl
    isExternal: true
    href: Sdl.html
  - name: .
  - uid: Sdl.MultiTerm
    name: MultiTerm
    isExternal: true
    href: Sdl.MultiTerm.html
  - name: .
  - uid: Sdl.MultiTerm.TMO
    name: TMO
    isExternal: true
    href: Sdl.MultiTerm.TMO.html
  - name: .
  - uid: Sdl.MultiTerm.TMO.Interop
    name: Interop
    isExternal: true
    href: Sdl.MultiTerm.TMO.Interop.html
- uid: Sdl.MultiTerm.TMO.Interop.IApplication.LocalRepository
  commentId: P:Sdl.MultiTerm.TMO.Interop.IApplication.LocalRepository
  parent: Sdl.MultiTerm.TMO.Interop.IApplication
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.IApplication.html#Sdl_MultiTerm_TMO_Interop_IApplication_LocalRepository
  name: LocalRepository
  nameWithType: IApplication.LocalRepository
  fullName: Sdl.MultiTerm.TMO.Interop.IApplication.LocalRepository
- uid: Sdl.MultiTerm.TMO.Interop.IApplication.ServerRepository
  commentId: P:Sdl.MultiTerm.TMO.Interop.IApplication.ServerRepository
  parent: Sdl.MultiTerm.TMO.Interop.IApplication
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.IApplication.html#Sdl_MultiTerm_TMO_Interop_IApplication_ServerRepository
  name: ServerRepository
  nameWithType: IApplication.ServerRepository
  fullName: Sdl.MultiTerm.TMO.Interop.IApplication.ServerRepository
- uid: Sdl.MultiTerm.TMO.Interop.IApplication.MultiSearch
  commentId: P:Sdl.MultiTerm.TMO.Interop.IApplication.MultiSearch
  parent: Sdl.MultiTerm.TMO.Interop.IApplication
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.IApplication.html#Sdl_MultiTerm_TMO_Interop_IApplication_MultiSearch
  name: MultiSearch
  nameWithType: IApplication.MultiSearch
  fullName: Sdl.MultiTerm.TMO.Interop.IApplication.MultiSearch
- uid: Sdl.MultiTerm.TMO.Interop.IApplication
  commentId: T:Sdl.MultiTerm.TMO.Interop.IApplication
  parent: Sdl.MultiTerm.TMO.Interop
  isExternal: true
  href: Sdl.MultiTerm.TMO.Interop.IApplication.html
  name: IApplication
  nameWithType: IApplication
  fullName: Sdl.MultiTerm.TMO.Interop.IApplication
